version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017